export { default as NavBar } from './navbar/NavBar';
export { default as TripsList } from './trips/trip-list/TripsList';
export { default as Section } from "./section/Section";
export { default as TripForm } from "./trips/trip-form/TripForm";
export { default as Footer } from "./footer/Footer";
export { default as TripItem } from "./trips/trip-item/TripItem"
export { default as DocumentsBox } from "./boxes/documents-box/DocumentsBox";
export { default as MapBox } from "./boxes/map-box/MapBox";
export { default as DiaryBox } from "./boxes/travel-diary/DiaryBox";
